export const moreMoviedata = [
  {
    img: "https://pastposters.com/cdn/shop/files/conjuring-cinema-quad-movie-poster-_3_c9df05c1-d466-4985-b41d-52ad752c76a0.jpg?v=1730153023&width=990",
    title: "The Conjuring",
    info: "A chilling tale of paranormal investigators facing a demonic presence.",
    rating: 4.2,
    category: "Horror",
    videoUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o",
  },
  {
    img: "https://ntvb.tmsimg.com/assets/p22972321_v_h10_aa.jpg?w=1280&h=720",
    title: "Killers of the Flower Moon",
    info: "A gripping crime drama based on true events, exploring the Osage Nation murders.",
    rating: 4.5,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=EG0si5bSd6I",
  },
  {
    img: "https://www.mugenmilano.com/wp-content/uploads/2024/01/The-Creator--1536x864.webp",
    title: "The Creator",
    info: "A visually stunning sci-fi thriller set in a future AI-driven world, questioning humanity.",
    rating: 4.0,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=ex3C1-5Dhb8",
  },
  {
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/318a5c24-e3bd-4e62-b0b2-218ed339eb69/dg1qvqv-ad89e62d-f1ac-4906-aee4-292da3811d21.jpg/v1/fill/w_894,h_894,q_70,strp/oppenheimer_movie_poster_art_by_akshaypp89_dg1qvqv-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzMxOGE1YzI0LWUzYmQtNGU2Mi1iMGIyLTIxOGVkMzM5ZWI2OVwvZGcxcXZxdi1hZDg5ZTYyZC1mMWFjLTQ5MDYtYWVlNC0yOTJkYTM4MTFkMjEuanBnIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.a-CgWmxg9-bW5ceQA6cHIF_pIE009jwuHknj0uBPVeU",
    title: "Oppenheimer",
    info: "Christopher Nolan’s biopic on J. Robert Oppenheimer and the creation of the atomic bomb.",
    rating: 4.8,
    category: "Historical Drama",
    videoUrl: "https://www.youtube.com/watch?v=bK6ldnjE3Y0",
  },
  {
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/846a9086-8a40-43e0-aa10-2fc7d6d73730/dgclhaw-36c7ccdc-49fa-4f29-9a6c-e0b3229807c8.jpg/v1/fit/w_828,h_1186,q_70,strp/the_marvels__2023__textless_poster__04_screen_x_by_mintmovi3_dgclhaw-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTgzMyIsInBhdGgiOiJcL2ZcLzg0NmE5MDg2LThhNDAtNDNlMC1hYTEwLTJmYzdkNmQ3MzczMFwvZGdjbGhhdy0zNmM3Y2NkYy00OWZhLTRmMjktOWE2Yy1lMGIzMjI5ODA3YzguanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.b1izFZ72nPhzyJxnsK0-9kCt1RF_rBwNCLoSuZnr-aI",
    title: "The Marvels",
    info: "The latest in the Marvel Cinematic Universe, bringing together three powerful heroes.",
    rating: 4.3,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=wS_qbDztgVY",
  },
  {
    img: "https://4kwallpapers.com/images/walls/thumbs_3t/13263.jpg",
    title: "Five Nights at Freddy's",
    info: "A horror movie adaptation of the popular video game series about haunted animatronics.",
    rating: 4.1,
    category: "Horror",
    videoUrl: "https://www.youtube.com/watch?v=0VHn7Cc8v78",
  },
  {
    img: "https://img.freepik.com/premium-photo/barbie-movie-poster-design_861346-74788.jpg?w=996",
    title: "Barbie",
    info: "A fun, satirical look at Barbie's world with a deeper twist on societal norms.",
    rating: 4.0,
    category: "Comedy",
    videoUrl: "https://www.youtube.com/watch?v=pBk4NYhWNMM",
  },

  {
    img: "https://images.alphacoders.com/125/thumb-1920-1250041.jpg",
    title: "Spiderman:No Way Home",
    info: "Action and Science fiction, Peter Parker seeks help from Doctor Strange to undo his exposed identity.",
    rating: 4.6,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
  },
  {
    img: "https://ticketdirect.co.nz/wp-content/uploads/2024/06/deadpool-and-wolverine-poster-reald-3d-cropped.jpg",
    title: "Deadpool and Wolverine",
    info: "Action and Comedy, Deadpool teams up with Wolverine.",
    rating: 4.7,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=UMgb3hQCb08",
  },
  {
    img: "https://img.englishcinemakyiv.com/aGs3AQcRKfBQev_3VyULwpO0nE78Cw3QDAJdtvEmUuU/resize:fill:800:450:1:0/gravity:sm/aHR0cHM6Ly9leHBhdGNpbmVtYXByb2QuYmxvYi5jb3JlLndpbmRvd3MubmV0L2ltYWdlcy8xZDg1N2JmZC04OGZlLTQzNWEtYTAwNi0zMmIwYWE3M2JkZmYuanBn.jpg",
    title: "The Holdovers",
    info: "A unique comedy-drama about a boarding school student and his reluctant winter break companion.",
    rating: 4.2,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=AhKLpJmHhIg",
  },
  {
    img: "https://i.etsystatic.com/32917608/r/il/195839/5694351035/il_794xN.5694351035_1tnh.jpg",
    title: "Saltburn",
    info: "A dark comedy-drama exploring themes of wealth and class with some thriller elements.",
    rating: 4.1,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=DcV1CaY_yB4",
  },
  {
    img: "https://i0.wp.com/lostinmovies.co.uk/wp-content/uploads/2024/03/Nyad-2023.jpg?w=1200&ssl=1",
    title: "Nyad",
    info: "The true story of swimmer Diana Nyad's attempt to swim from Cuba to Florida in her 60s.",
    rating: 4.3,
    category: "Biography",
    videoUrl: "https://www.youtube.com/watch?v=r5gqFwG_GiU",
  },
  {
    img: "https://static.wixstatic.com/media/52313f_23a386c0f1324cdd833bd77c6c8f2132~mv2.png/v1/fill/w_490,h_490,fp_0.50_0.50,q_85,usm_0.66_1.00_0.01,enc_auto/52313f_23a386c0f1324cdd833bd77c6c8f2132~mv2.png",
    title: "Next Goal Wins",
    info: "A feel-good sports comedy about the American Samoa soccer team's comeback.",
    rating: 4.0,
    category: "Sports Comedy",
    videoUrl: "https://www.youtube.com/watch?v=b-nUTKu60u4",
  },
  {
    img: "https://cscsnews.com/wp-content/uploads/2023/12/zxdbwDM4vzGvo7KwtnNwO6oC2bOV9lGGGTLKRKFu-1200x1193.jpg",
    title: "Priscilla",
    info: "A Sofia Coppola-directed biopic about Priscilla Presley's relationship with Elvis.",
    rating: 4.4,
    category: "Biography",
    videoUrl: "https://www.youtube.com/watch?v=L8gM-f0j5uM",
  },
  {
    img: "https://static.toiimg.com/thumb/msid-112274362,imgsize-68790,width-400,resizemode-4/112274362.jpg",
    title: "Fast and Furious",
    info: "Its a Series",
    rating: 4.3,
    category: "Action",
    videoUrl: "https://www.youtube.com/watch?v=32RAq6JzY-w",
  },
  {
    img: "https://image.jimcdn.com/app/cms/image/transf/none/path/s44063efe23c3239b/image/i1e488df3c538cc31/version/1483692379/image.png",
    title: "Whiplash",
    info: "An electrifying and emotionally charged story with brilliant performances. The film's tension-filled narrative and exhilarating music sequences are unforgettable.",
    rating: 4.9,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=7d_jQycdQGo",
  },
  {
    img: "https://www.hdwallpapers.net/previews/interstellar-the-movie-475.jpg",
    title: "Interstellar",
    info: "This visually stunning epic combines science and emotion, featuring a thought-provoking story, Hans Zimmer's haunting score, and outstanding performances by the cast.",
    rating: 4.7,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=2LqzF5WauAw",
  },
  {
    img: "https://wallpapercave.com/wp/wp13210862.jpg",
    title: "Napoleon",
    info: "A historical epic directed by Ridley Scott, focusing on Napoleon Bonaparte.",
    rating: 4.5,
    category: "Historical Drama",
    videoUrl: "https://www.youtube.com/watch?v=OAZWXUkrjPc",
  },

  {
    img: "https://images.squarespace-cdn.com/content/v1/5ec686197f8b2976074846c2/1618809593080-N5PB8CWYOW3OPDE2TT6E/Feature+3-1.png?format=2500w",
    title: "Inception",
    info: "A mind-bending sci-fi thriller with unforgettable visuals and storytelling.",
    rating: 4.8,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
  },
  {
    img: "https://i.redd.it/x1ihw7kcn0r21.jpg",
    title: "Parasite",
    info: " A dark comedy-thriller that explores class disparity in South Korea.",
    rating: 4.6,
    category: "Thriller",
    videoUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
  },
  {
    img: "https://images.alphacoders.com/547/thumb-1920-547409.jpg",
    title: "The Grand Budapest Hotel",
    info: "Wes Anderson's quirky, visually unique comedy-drama.",
    rating: 4.4,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=1Fg5iWmQjwk",
  },
  {
    img: "https://i.etsystatic.com/47325174/r/il/c6a3b0/5556719109/il_794xN.5556719109_dp1g.jpg",
    title: "The Shawshank Redemption",
    info: "A classic tale of hope and friendship set in prison.",
    rating: 4.9,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVofIotjHIAodWTN_mVaRxlH8lWOZgwK1eZQ&s",
    title: "Spirited Away",
    info: "A beautifully animated Japanese film about a young girl's journey in a mystical world.",
    rating: 4.8,
    category: "Animation",
    videoUrl: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
  },

  // change imgUrls

  {
    img: "https://upload.wikimedia.org/wikipedia/en/1/14/Everything_Everywhere_All_at_Once.jpg",
    title: "Everything Everywhere All at Once",
    info: "A mind-bending action-comedy about a woman who must connect with parallel universe versions of herself to prevent a powerful being from destroying the multiverse.",
    rating: 4.7,
    category: "Action, Comedy, Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/3/36/Dune_%282021_film%29.jpg",
    title: "Dune",
    info: "A mythic and emotionally charged hero’s journey, Dune tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, who must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    rating: 4.6,
    category: "Sci-Fi, Adventure",
    videoUrl: "https://www.youtube.com/watch?v=n9xhJrPXop4",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/8/86/Top_Gun_Maverick.jpg",
    title: "Top Gun: Maverick",
    info: "After more than thirty years of service as one of the Navy’s top aviators, Pete “Maverick” Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    rating: 4.8,
    category: "Action, Drama",
    videoUrl: "https://www.youtube.com/watch?v=qSqVVswa420",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/2/25/Knives_Out_%282019_film%29.png",
    title: "Knives Out",
    info: "A detective investigates the death of a patriarch of an eccentric, combative family.",
    rating: 4.4,
    category: "Comedy, Crime, Mystery",
    videoUrl: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/d/d6/Black_Panther_%28film%29_poster.jpg",
    title: "Black Panther",
    info: "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people in a new era and must confront challenges from factions within his own country as well as enemies from abroad.",
    rating: 4.7,
    category: "Action, Adventure, Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/2/22/John_Wick_TeaserPoster.jpg",
    title: "John Wick",
    info: "An ex-hitman comes out of retirement to track down the gangsters that took everything from him.",
    rating: 4.5,
    category: "Action, Neo-noir, Thriller",
    videoUrl: "https://www.youtube.com/watch?v=2AUmvWm5ZDQ",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg",
    title: "Mad Max: Fury Road",
    info: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshipper, and a drifter named Max.",
    rating: 4.8,
    category: "Action, Sci-Fi, Adventure",
    videoUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/f/fa/Baby_Driver_poster.jpg",
    title: "Baby Driver",
    info: "A talented young getaway driver relies on the beat of his personal soundtrack to be the best in the game.",
    rating: 4.4,
    category: "Action, Crime, Music",
    videoUrl: "https://www.youtube.com/watch?v=D9YZw_x_vHE",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/a/a4/Into_the_Spider-Verse_poster.png",
    title: "Spider-Man: Into the Spider-Verse",
    info: "Teen Miles Morales becomes Spider-Man of his dimension, crossing his path with five counterparts from other dimensions to stop a threat for all realities.",
    rating: 4.7,
    category: "Animation, Action, Adventure",
    videoUrl: "https://www.youtube.com/watch?v=g4Hbz2jLxvQ",
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/en/1/17/Logan_2017_poster.jpg",
    title: "Logan",
    info: "In the near future, a weary Logan cares for an ailing Professor X, somewhere on the Mexican border. However, Logan's attempts to hide from the world, and his legacy, are upended when a young mutant arrives, pursued by dark forces.",
    rating: 4.6,
    category: "Action, Drama, Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=DekuSxJgpbY",
  },
];

export const moviedata = [
  {
    img: "https://pastposters.com/cdn/shop/files/conjuring-cinema-quad-movie-poster-_3_c9df05c1-d466-4985-b41d-52ad752c76a0.jpg?v=1730153023&width=990",
    title: "The Conjuring",
    info: "Its a Horror Movies.....Dont Watch alone",
    rating: "4.2",
    category: "Horror",
    videoUrl: "https://www.youtube.com/watch?v=k10ETZ41q5o",
  },
  {
    img: "https://ntvb.tmsimg.com/assets/p22972321_v_h10_aa.jpg?w=1280&h=720",
    title: "Killers of the Flower Moon",
    info: "A gripping crime drama based on true events",
    rating: 4.5,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=HAR21WUUyR8",
  },
  {
    img: "https://www.mugenmilano.com/wp-content/uploads/2024/01/The-Creator--1536x864.webp",
    title: "The Creator",
    info: "A visually stunning sci-fi thriller set in a future AI-driven world.",
    rating: 4.0,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=ex3C1-5Dhb8",
  },
  {
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/318a5c24-e3bd-4e62-b0b2-218ed339eb69/dg1qvqv-ad89e62d-f1ac-4906-aee4-292da3811d21.jpg/v1/fill/w_894,h_894,q_70,strp/oppenheimer_movie_poster_art_by_akshaypp89_dg1qvqv-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTA4MCIsInBhdGgiOiJcL2ZcLzMxOGE1YzI0LWUzYmQtNGU2Mi1iMGIyLTIxOGVkMzM5ZWI2OVwvZGcxcXZxdi1hZDg5ZTYyZC1mMWFjLTQ5MDYtYWVlNC0yOTJkYTM4MTFkMjEuanBnIiwid2lkdGgiOiI8PTEwODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.a-CgWmxg9-bW5ceQA6cHIF_pIE009jwuHknj0uBPVeU",
    title: "Oppenheimer",
    info: "Christopher Nolan’s biopic on J. Robert Oppenheimer and the creation of the atomic bomb.",
    rating: 4.8,
    category: "Historical Drama",
    videoUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg",
  },
  {
    img: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/846a9086-8a40-43e0-aa10-2fc7d6d73730/dgclhaw-36c7ccdc-49fa-4f29-9a6c-e0b3229807c8.jpg/v1/fit/w_828,h_1186,q_70,strp/the_marvels__2023__textless_poster__04_screen_x_by_mintmovi3_dgclhaw-414w-2x.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTgzMyIsInBhdGgiOiJcL2ZcLzg0NmE5MDg2LThhNDAtNDNlMC1hYTEwLTJmYzdkNmQ3MzczMFwvZGdjbGhhdy0zNmM3Y2NkYy00OWZhLTRmMjktOWE2Yy1lMGIzMjI5ODA3YzguanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.b1izFZ72nPhzyJxnsK0-9kCt1RF_rBwNCLoSuZnr-aI",
    title: "The Marvels",
    info: "The latest in the Marvel Cinematic Universe, bringing together three powerful heroes.",
    rating: 4.3,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://4kwallpapers.com/images/walls/thumbs_3t/13263.jpg",
    title: "Five Nights at Freddy's",
    info: "A horror movie adaptation of the popular video game series.",
    rating: 4.1,
    category: "Horror",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://img.freepik.com/premium-photo/barbie-movie-poster-design_861346-74788.jpg?w=996",
    title: "Barbie ",
    info: "A fun, satirical look at Barbie's world with a deeper twist on societal norms.",
    rating: 4.0,
    category: "Comedy",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
];
export const moviedata2 = [
  {
    img: "https://images.alphacoders.com/125/thumb-1920-1250041.jpg",
    title: "Spiderman:No Way Home",
    info: "Action and Science fiction",
    rating: 4.6,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=JfVOs4VSpmA",
  },
  {
    img: "https://ticketdirect.co.nz/wp-content/uploads/2024/06/deadpool-and-wolverine-poster-reald-3d-cropped.jpg",
    title: "Deadpool and Woolverine",
    info: "Action and Comedy",
    rating: 4.7,
    category: "Superhero",
    videoUrl: "https://www.youtube.com/watch?v=UMgb3hQCb08",
  },
  {
    img: "https://img.englishcinemakyiv.com/aGs3AQcRKfBQev_3VyULwpO0nE78Cw3QDAJdtvEmUuU/resize:fill:800:450:1:0/gravity:sm/aHR0cHM6Ly9leHBhdGNpbmVtYXByb2QuYmxvYi5jb3JlLndpbmRvd3MubmV0L2ltYWdlcy8xZDg1N2JmZC04OGZlLTQzNWEtYTAwNi0zMmIwYWE3M2JkZmYuanBn.jpg",
    title: "The Holdovers",
    info: " A unique comedy-drama about a boarding school student and his reluctant winter break companion.",
    rating: 4.2,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://i.etsystatic.com/32917608/r/il/195839/5694351035/il_794xN.5694351035_1tnh.jpg",
    title: "Saltburn",
    info: "A dark comedy-drama exploring themes of wealth and class with some thriller elements.",
    rating: 4.1,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://i0.wp.com/lostinmovies.co.uk/wp-content/uploads/2024/03/Nyad-2023.jpg?w=1200&ssl=1",
    title: "Nyad",
    info: "The true story of swimmer Diana Nyad's attempt to swim from Cuba to Florida in her 60s.",
    rating: 4.3,
    category: "Biography",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://static.wixstatic.com/media/52313f_23a386c0f1324cdd833bd77c6c8f2132~mv2.png/v1/fill/w_490,h_490,fp_0.50_0.50,q_85,usm_0.66_1.00_0.01,enc_auto/52313f_23a386c0f1324cdd833bd77c6c8f2132~mv2.png",
    title: " Next Goal Wins.",
    info: "A feel-good sports comedy about the American Samoa soccer team's comeback.",
    rating: 4.0,
    category: "Sports Comedy",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
  {
    img: "https://cscsnews.com/wp-content/uploads/2023/12/zxdbwDM4vzGvo7KwtnNwO6oC2bOV9lGGGTLKRKFu-1200x1193.jpg",
    title: "Priscilla",
    info: "A Sofia Coppola-directed biopic about Priscilla Presley's relationship with Elvis.",
    rating: 4.4,
    category: "Biography",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },
];
export const moviedata3 = [
  {
    img: "https://static.toiimg.com/thumb/msid-112274362,imgsize-68790,width-400,resizemode-4/112274362.jpg",
    title: "Fast and Furious",
    info: "Its a Series",
    rating: 4.3,
    category: "Action",
    videoUrl: "https://www.youtube.com/watch?v=32RAq6JzY-w",
  },
  {
    img: "https://image.jimcdn.com/app/cms/image/transf/none/path/s44063efe23c3239b/image/i1e488df3c538cc31/version/1483692379/image.png",
    title: "Whiplash",
    info: "An electrifying and emotionally charged story with brilliant performances, particularly by J.K. Simmons, who won an Academy Award for his role. The film's tension-filled narrative and exhilarating music sequences are unforgettable.",
    rating: 4.9,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=7d_jQycdQGo",
  },
  {
    img: "https://www.hdwallpapers.net/previews/interstellar-the-movie-475.jpg",
    title: "Interstellar",
    info: "This visually stunning epic combines science and emotion, featuring a thought-provoking story, Hans Zimmer's haunting score, and outstanding performances by the cast.",
    rating: 4.7,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=2LqzF5WauAw",
  },
  {
    img: "https://wallpapercave.com/wp/wp13210862.jpg",
    title: "Napoleon",
    info: "A historical epic directed by Ridley Scott, focusing on Napoleon Bonaparte.",
    rating: 4.5,
    category: "Historical Drama",
    videoUrl: "https://www.youtube.com/watch?v=Z1pxiQ3uK0I",
  },

  {
    img: "https://images.squarespace-cdn.com/content/v1/5ec686197f8b2976074846c2/1618809593080-N5PB8CWYOW3OPDE2TT6E/Feature+3-1.png?format=2500w",
    title: "Inception",
    info: "A mind-bending sci-fi thriller with unforgettable visuals and storytelling.",
    rating: 4.8,
    category: "Sci-Fi",
    videoUrl: "https://www.youtube.com/watch?v=YoHD9XEInc0",
  },
  {
    img: "https://i.redd.it/x1ihw7kcn0r21.jpg",
    title: "Parasite",
    info: " A dark comedy-thriller that explores class disparity in South Korea.",
    rating: 4.6,
    category: "Thriller",
    videoUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
  },
  {
    img: "https://images.alphacoders.com/547/thumb-1920-547409.jpg",
    title: "The Grand Budapest Hotel",
    info: "Wes Anderson's quirky, visually unique comedy-drama.",
    rating: 4.4,
    category: "Comedy-Drama",
    videoUrl: "https://www.youtube.com/watch?v=1Fg5iWmQjwk",
  },
  {
    img: "https://i.etsystatic.com/47325174/r/il/c6a3b0/5556719109/il_794xN.5556719109_dp1g.jpg",
    title: "The Shawshank Redemption",
    info: "A classic tale of hope and friendship set in prison.",
    rating: 4.9,
    category: "Drama",
    videoUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVofIotjHIAodWTN_mVaRxlH8lWOZgwK1eZQ&s",
    title: "Spirited Away",
    info: "A beautifully animated Japanese film about a young girl's journey in a mystical world.",
    rating: 4.8,
    category: "Animation",
    videoUrl: "https://www.youtube.com/watch?v=ByXuk9QqQkk",
  },
];
